In [1]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in d:\genAi_tutedude\.venv\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in d:\genAi_tutedude\.venv\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\genAi_tutedude\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\genAi_tutedude\.venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in d:\genAi_tutedude\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
students = {
    'Name': ['Amit', 'Neha', 'Rahul', 'Sneha', 'Pooja'],
    'Marks': [78, 85, 90, 66, 72],
    'Subject': ['Math', 'Math', 'Science', 'Science', 'Math']
}

df = pd.DataFrame(students)
df

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Marks    5 non-null      int64
 2   Subject  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [4]:
df.describe()

           Marks
count   5.000000
mean   78.200000
std     9.654015
min    66.000000
25%    72.000000
50%    78.000000
75%    85.000000
max    90.000000

In [5]:
df.head()

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [7]:
df.tail()

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [9]:
df_sorted = df.sort_values(by='Marks', ascending=False)
df_sorted

    Name  Marks  Subject
2  Rahul     90  Science
1   Neha     85     Math
0   Amit     78     Math
4  Pooja     72     Math
3  Sneha     66  Science

In [10]:
df_sorted = df_sorted.reset_index(drop=True)
df_sorted

    Name  Marks  Subject
0  Rahul     90  Science
1   Neha     85     Math
2   Amit     78     Math
3  Pooja     72     Math
4  Sneha     66  Science