In [2]:
!pip install  pandas
import pandas as pd

Requirement already satisfied: pandas in d:\genAi_tutedude\.venv\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in d:\genAi_tutedude\.venv\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\genAi_tutedude\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\genAi_tutedude\.venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in d:\genAi_tutedude\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
students = {
    'Name': ['Amit', 'Neha', 'Rahul', 'Sneha', 'Pooja'],
    'Marks': [78, 85, 90, 66, 72],
    'Subject': ['Math', 'Math', 'Science', 'Science', 'Math']
}

df = pd.DataFrame(students)
df

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [4]:
scores_greater_than_75 = df[df['Marks'] > 75]
print(scores_greater_than_75)

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science

In [5]:
df[df['Subject'] == 'Math']

    Name  Marks Subject
0   Amit     78    Math
1   Neha     85    Math
4  Pooja     72    Math

In [6]:
df[df['Marks'] > df['Marks'].mean()]

    Name  Marks  Subject
1   Neha     85     Math
2  Rahul     90  Science

In [7]:
df[df['Marks'] < 70]

    Name  Marks  Subject
3  Sneha     66  Science